### ISSUE TITLE
See nothing in Umbraco  7.2.6

### ISSUE THREAD

**Issue by wroughtec** [ViGiLnT/ApproveIt#1]
When I click on the approve it icon the Start here panel shows but the left column stays as whatever it was last on eg content.

When I refresh the page I get a blank white column next to the start here panel any advice?

**Comment by ViGiLnT** [comment]
Hi wroughtec. Sorry I didn't answer before.

I've just updated the code to use Umbraco 7.3 and everything is working the same... So the problem you were facing probably had to do with cache. Most problems I had while developing the plugin had to do with cache. So what I recommend is to always test changes to the BO in browser private mode.

Thanks
